language: ruby
sudo: false
dist: trusty
cache: bundler
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
- jruby-head
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
env:
  global:
    secure: LU7mGKnIrWrnrdtq7Ug7HTxzqJoB+NbLHwT8dPmGf4GIfNosO4Jx+G4JLzUd/sCHzUR+XXrsMd7El8WkTVV28+nt6Cv2JvO4EJRIplnAL8Yauc0YSWRwA9nGYhcc2TJc5czbL0mZkJSOv4B+aWco0VWerJfgLYurIA05XrQFGGY=
